### ISSUE TITLE
invalid EOL character

### ISSUE THREAD

**Issue by ak4t0sh** [edloomio/moodle-compliance-plugin#6]
It seems that your editor is configured to use `\r` as EOL (End of line) character.
You have to change it to `\n` and save (almost all) your files again.

You can figure out which file by implementing #1 or finding files which appear on one line on GitHub interface. 
Example : [index.php#L1](https://github.com/edloomio/moodle-compliance-plugin/blob/e8c6842241fb61b3a5ab3f1d3d29b35a536ada6b/index.php#L1)

**Comment by rajuptl21** [comment]
I have fixed highlighted issue.
